apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil42-playground
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://10.42.0.17/root/t.git'
    targetRevision: '7ca0d59406b2007e34887c34378af6725b7fa31b'
    path: 'p3/confs/sync'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
