## VARIABLES
CONTROLLER_IP = "192.168.56.110"

CONTROLLER_NAME = "bapasquiS"

MEM = 4096
CORE = 3

## VAGRANT CONFIG
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  
  config.vm.define CONTROLLER_NAME do |controller|
    controller.vm.hostname = CONTROLLER_NAME
    controller.vm.provider "virtualbox" do |v|
      v.memory = MEM
      v.cpus = CORE
      v.name = CONTROLLER_NAME
    end
    controller.vm.network "private_network", type: "static", ip: CONTROLLER_IP, interface: "eth1"
    controller.vm.provision "shell", path: "scripts/server.sh", args: [CONTROLLER_IP]
    controller.vm.provision "shell", path: "scripts/setup.sh"
  end
end
