Vagrant.configure("2") do |config| 

  # SERVER CONFIGURATION
  config.vm.define "hbelleS" do |server|
    server.vm.box = "debian/bullseye64"
    server.vm.network "private_network", ip: "192.168.56.110", interface: "eth1"
    server.vm.network "forwarded_port", guest: 22, host: 4242, id: "ssh"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "hbelleS"
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.synced_folder "./conf", "/vagrant", type: "nfs", nfs_version: 4
    server.vm.provision "shell", inline: <<-SHELL
      set -x
      sudo apt-get update
      sudo apt-get install -y curl
      # Installer K3s en tant que serveur maître avec un nom de nœud spécifique
      curl -sSL https://get.k3s.io | sh -s - server --node-ip 192.168.56.110 --node-name hbelleS

      # Copier le fichier kubeconfig pour l'accès externe
      sudo cp /etc/rancher/k3s/k3s.yaml /vagrant/kubeconfig

      # Modifier l'adresse IP dans le fichier kubeconfig
      sed -i "s/127\\.0\\.0\\.1/192.168.56.110/" /vagrant/kubeconfig

      # Configmap pour les applications
      sudo kubectl apply -f /vagrant/app1/configmap-app1.yaml
      sudo kubectl apply -f /vagrant/app2/configmap-app2.yaml
      sudo kubectl apply -f /vagrant/app3/configmap-app3.yaml

      # Déploiement des services
      sudo kubectl apply -f /vagrant/app1/service-app1.yaml
      sudo kubectl apply -f /vagrant/app2/service-app2.yaml
      sudo kubectl apply -f /vagrant/app3/service-app3.yaml

      # Attente de 30 secondes pour que les services soient prêts
      sleep 30
      
      # Déploiement des pods
      sudo kubectl apply -f /vagrant/app1/deployment-app1.yaml
      sudo kubectl apply -f /vagrant/app2/deployment-app2.yaml
      sudo kubectl apply -f /vagrant/app3/deployment-app3.yaml

      # Déploiement de l'ingress
      sudo kubectl apply -f /vagrant/ingress.yaml

    SHELL
  end
end