Vagrant.configure("2") do |config| 

  # SERVER CONFIGURATION
  config.vm.define "hbelleS" do |server|
    server.vm.box = "debian/bullseye64"
    server.vm.network "private_network", ip: "192.168.56.110", interface: "eth1"
    server.vm.network "forwarded_port", guest: 22, host: 4242, id: "ssh"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "hbelleS"
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.synced_folder "./conf", "/vagrant/conf", type: "nfs", nfs_version: 4
    server.vm.synced_folder "./scripts", "/vagrant/scripts", type: "nfs", nfs_version: 4
    server.vm.provision "shell", inline: <<-SHELL
      bash /vagrant/scripts/script_master.sh
    SHELL
  end
end