Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "dboireS" do |machine_one|
    machine_one.vm.hostname = "dboireS"
    machine_one.vm.network "private_network", ip: "192.168.56.110"

    machine_one.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive

      sudo apt-get update
      sudo apt-get install -y curl

      curl -sSL https://get.k3s.io | sh -s - server --node-ip 192.168.56.110 --node-name dboireS

      sudo mkdir -p /vagrant/confs

      sudo cp /etc/rancher/k3s/k3s.yaml /vagrant/confs/kubeconfig
      sudo sed -i "s/127\\.0\\.0\\.1/192.168.56.110/" /vagrant/confs/kubeconfig

      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/confs/node-token
    SHELL

    machine_one.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  config.vm.define "hbelleSW" do |machine_two|
    machine_two.vm.hostname = "hbelleSW"  # Set a unique hostname
    machine_two.vm.network "private_network", ip: "192.168.56.111"

    machine_two.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive

      echo "Updating package list..."
      sudo apt-get update
      echo "Installing curl..."
      sudo apt-get install -y curl

      echo "Waiting for node-token file..."
      while [ ! -f /vagrant/confs/node-token ]; do sleep 1; done
      echo "node-token file found. Attempting to join the cluster..."

      K3S_TOKEN=$(cat /vagrant/confs/node-token)
      echo "K3S_TOKEN: $K3S_TOKEN"
      
      while true; do
        curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$K3S_TOKEN sh -s - agent --node-ip 192.168.56.111 --node-name hbelleSW
        if [ $? -eq 0 ]; then
          echo "Successfully joined the cluster."
          break
        else
          echo "Failed to join the cluster. Retrying in 2 seconds..."
          sleep 2
        fi
      done
    SHELL

    machine_two.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end
