
FileUtils.mkdir_p('./confs')

Vagrant.configure("2") do |config| 

  # SERVER CONFIGURATION
  config.vm.define "hbelleS" do |server|
    server.vm.box = "debian/bullseye64"
    server.vm.network "private_network", ip: "192.168.56.110", interface: "eth1"
    server.vm.network "forwarded_port", guest: 22, host: 4242, id: "ssh"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "hbelleS"
      vb.memory = "1024"
      vb.cpus = 1
    end

    server.vm.synced_folder "./confs", "/vagrant/confs", type: "nfs", nfs_version: 4
    server.vm.synced_folder "./scripts", "/vagrant/scripts", type: "nfs", nfs_version: 4
    server.vm.provision "shell", inline: <<-SHELL
      bash /vagrant/scripts/script_master.sh
    SHELL
  end

  # SERVER WORKER CONFIGURATION
  config.vm.define "hbelleSW" do |serverWorker|
    serverWorker.vm.box = "debian/bullseye64"
    serverWorker.vm.network "private_network", ip: "192.168.56.111", interface: "eth1"
    serverWorker.vm.network "forwarded_port", guest: 22, host: 4243, id: "ssh"
    serverWorker.vm.provider "virtualbox" do |vb|
      vb.name = "hbelleSW"
      vb.memory = "1024"
      vb.cpus = 1
    end
    serverWorker.vm.synced_folder "./confs", "/vagrant/confs", type: "nfs", nfs_version: 4
    serverWorker.vm.synced_folder "./scripts", "/vagrant/scripts", type: "nfs", nfs_version: 4
    serverWorker.vm.provision "shell", inline: <<-SHELL
      bash /vagrant/scripts/script_worker.sh
    SHELL
  end
end